// Database schema as numbered migrations. Each runs once, in order, inside a transaction;
// an advisory lock keeps two starting app servers from migrating at the same time.
// Add a new migration at the end — never edit one that has already run in production.
import { DEFAULT_PLAN } from './plans.js';

if (!/^[a-z_]+$/.test(DEFAULT_PLAN)) throw new Error('Unexpected default plan id');

const MIGRATIONS = [
  // 1: accounts, birth data, plans, profiles of close people, consented chat history, metrics, orders.
  `
  CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    email_verified_at BIGINT,
    display_name TEXT,
    plan TEXT NOT NULL DEFAULT '${DEFAULT_PLAN}',
    plan_expires_at BIGINT,
    chat_history_consent_at BIGINT,
    autorenew_method_id TEXT,
    autorenew_provider TEXT,
    autorenew_currency TEXT
  );
  CREATE TABLE sessions (
    token_hash TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at BIGINT NOT NULL
  );
  CREATE INDEX sessions_expiry ON sessions(expires_at);
  CREATE INDEX sessions_user ON sessions(user_id);
  CREATE TABLE birth_profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    birth_date TEXT NOT NULL, birth_time TEXT NOT NULL, birth_place TEXT NOT NULL, city_id BIGINT,
    birth_latitude DOUBLE PRECISION, birth_longitude DOUBLE PRECISION, birth_time_zone TEXT, birth_utc TEXT,
    birth_utc_offset_minutes INTEGER, updated_at BIGINT NOT NULL
  );
  CREATE TABLE auth_challenges (
    challenge_hash TEXT PRIMARY KEY,
    purpose TEXT NOT NULL CHECK (purpose IN ('registration', 'verify', 'reset')),
    email TEXT NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    password_hash TEXT, code_hash TEXT NOT NULL, expires_at BIGINT NOT NULL,
    attempts_left INTEGER NOT NULL, last_sent_at BIGINT NOT NULL,
    UNIQUE (purpose, email)
  );
  CREATE INDEX auth_challenges_expiry ON auth_challenges(expires_at);
  CREATE TABLE daily_quotas (
    kind TEXT NOT NULL, day TEXT NOT NULL, used INTEGER NOT NULL, PRIMARY KEY (kind, day)
  );
  CREATE TABLE chart_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    relation TEXT NOT NULL, label TEXT NOT NULL,
    birth_date TEXT NOT NULL, birth_time TEXT NOT NULL, birth_place TEXT NOT NULL, city_id BIGINT,
    birth_latitude DOUBLE PRECISION, birth_longitude DOUBLE PRECISION, birth_time_zone TEXT, birth_utc TEXT,
    birth_utc_offset_minutes INTEGER, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL
  );
  CREATE INDEX chart_profiles_user ON chart_profiles(user_id, id);
  CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    profile_id BIGINT REFERENCES chart_profiles(id) ON DELETE SET NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL, created_at BIGINT NOT NULL
  );
  CREATE INDEX chat_messages_user ON chat_messages(user_id, id);
  CREATE TABLE metrics_daily (
    day TEXT NOT NULL, metric TEXT NOT NULL, value BIGINT NOT NULL, PRIMARY KEY (day, metric)
  );
  CREATE TABLE visitors_daily (
    day TEXT NOT NULL, visitor TEXT NOT NULL, PRIMARY KEY (day, visitor)
  );
  -- Numeric invoice numbers for providers that cannot take a UUID (Robokassa InvId).
  CREATE SEQUENCE orders_invoice_seq;
  CREATE TABLE orders (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    product_id TEXT NOT NULL, plan TEXT NOT NULL, period_days INTEGER NOT NULL,
    amount_kop BIGINT NOT NULL CHECK (amount_kop > 0), currency TEXT NOT NULL DEFAULT 'RUB',
    status TEXT NOT NULL CHECK (status IN ('pending', 'paid', 'canceled', 'failed', 'refunded')),
    provider TEXT NOT NULL, provider_payment_id TEXT UNIQUE,
    invoice_no BIGINT NOT NULL UNIQUE DEFAULT nextval('orders_invoice_seq'),
    auto_renew BOOLEAN NOT NULL DEFAULT FALSE, renewal BOOLEAN NOT NULL DEFAULT FALSE,
    created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL, paid_at BIGINT
  );
  CREATE INDEX orders_user ON orders(user_id, created_at);
  CREATE INDEX orders_pending ON orders(created_at) WHERE status = 'pending';
  CREATE TABLE payment_events (
    provider TEXT NOT NULL, event_key TEXT NOT NULL, received_at BIGINT NOT NULL, PRIMARY KEY (provider, event_key)
  );
  `,
];

const MIGRATION_LOCK = 71_412_026; // any constant shared by all app servers

export async function migrate(db) {
  await db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at BIGINT NOT NULL)');
  await db.transaction(async (tx) => {
    await tx.query('SELECT pg_advisory_xact_lock($1)', [MIGRATION_LOCK]);
    const done = new Set((await tx.query('SELECT version FROM schema_migrations')).map((row) => row.version));
    for (const [index, sql] of MIGRATIONS.entries()) {
      const version = index + 1;
      if (done.has(version)) continue;
      for (const statement of sql.split(/;\s*\n/).map((part) => part.trim()).filter(Boolean)) await tx.query(statement);
      await tx.query('INSERT INTO schema_migrations (version, applied_at) VALUES ($1, $2)', [version, Date.now()]);
    }
  });
}

export const SCHEMA_VERSION = MIGRATIONS.length;
